# Generated by Django 5.2.5 on 2025-11-27 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(blank=True, help_text='Humidity percentage', null=True)),
                ('soil_moisture', models.FloatField(help_text='Soil moisture percentage')),
                ('soil_ph', models.FloatField(help_text='Soil pH value')),
                ('ec', models.FloatField(help_text='Electrical Conductivity')),
                ('nitrogen', models.FloatField(help_text='Nitrogen level')),
                ('phosphorus', models.FloatField(help_text='Phosphorus level')),
                ('potassium', models.FloatField(help_text='Potassium level')),
                ('recommended_fertilizer', models.CharField(help_text='Recommended fertilizer name/type', max_length=255)),
                ('fertilizer_amount', models.FloatField(blank=True, help_text='Recommended amount in kg/hectare', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Prediction confidence score (0-1)', null=True)),
                ('recommendation_details', models.TextField(blank=True, help_text='Detailed recommendation explanation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fertilizer Prediction',
                'verbose_name_plural': 'Fertilizer Predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
