# Generated by Django 5.2.5 on 2025-11-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizerprediction',
            old_name='soil_moisture',
            new_name='moisture',
        ),
        migrations.RenameField(
            model_name='fertilizerprediction',
            old_name='phosphorus',
            new_name='phosphorous',
        ),
        migrations.AddField(
            model_name='fertilizerprediction',
            name='crop_type',
            field=models.CharField(blank=True, help_text='Crop type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fertilizerprediction',
            name='soil_type',
            field=models.CharField(blank=True, help_text='Soil type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizerprediction',
            name='ec',
            field=models.FloatField(blank=True, help_text='Electrical Conductivity', null=True),
        ),
        migrations.AlterField(
            model_name='fertilizerprediction',
            name='soil_ph',
            field=models.FloatField(blank=True, help_text='Soil pH value', null=True),
        ),
    ]
