# Generated by Django 5.2.5 on 2025-09-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='action',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('logout', 'Logout'), ('update_profile', 'Profile Update'), ('change_password', 'Change Password'), ('other', 'Other')], max_length=50),
        ),
    ]
